# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-04-01 22:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajador',
            name='imagen',
            field=models.ImageField(null=True, upload_to='photos'),
        ),
    ]
